-- Seed the public Benefits page with driver welfare schemes.
INSERT INTO public.schemes (
  id,
  title_en,
  title_ta,
  title_hi,
  description_en,
  description_ta,
  description_hi,
  level,
  category,
  target_workers,
  max_benefit_amount,
  benefit_unit,
  eligibility_summary_en,
  eligibility_summary_ta,
  eligibility_summary_hi,
  official_link,
  is_active
) VALUES
(
  '10000000-0000-4000-8000-000000000001',
  'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana',
  'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana',
  'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana',
  'Health insurance scheme providing coverage up to INR 5 lakh per family per year for secondary and tertiary care hospitalization.',
  'Health insurance scheme providing coverage up to INR 5 lakh per family per year for secondary and tertiary care hospitalization.',
  'Health insurance scheme providing coverage up to INR 5 lakh per family per year for secondary and tertiary care hospitalization.',
  'central',
  'Healthcare',
  'Eligible driver families and low-income households.',
  500000,
  'INR/year',
  'Eligible families as per government beneficiary database',
  'Eligible families as per government beneficiary database',
  'Eligible families as per government beneficiary database',
  'https://beneficiary.nha.gov.in/',
  true
),
(
  '10000000-0000-4000-8000-000000000002',
  'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
  'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
  'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
  'Accidental death and disability insurance scheme providing coverage for accidental death, total disability, and partial disability.',
  'Accidental death and disability insurance scheme providing coverage for accidental death, total disability, and partial disability.',
  'Accidental death and disability insurance scheme providing coverage for accidental death, total disability, and partial disability.',
  'central',
  'Insurance',
  'Drivers and other workers with a savings bank account.',
  200000,
  'INR',
  'Age 18-70, savings bank account, consent for auto-debit',
  'Age 18-70, savings bank account, consent for auto-debit',
  'Age 18-70, savings bank account, consent for auto-debit',
  'https://www.jansuraksha.gov.in/',
  true
),
(
  '10000000-0000-4000-8000-000000000003',
  'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
  'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
  'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
  'Life insurance scheme providing coverage in case of death due to any reason with a low annual premium.',
  'Life insurance scheme providing coverage in case of death due to any reason with a low annual premium.',
  'Life insurance scheme providing coverage in case of death due to any reason with a low annual premium.',
  'central',
  'Insurance',
  'Drivers and other workers with a savings bank account.',
  200000,
  'INR',
  'Age 18-50, savings bank account, consent for auto-debit',
  'Age 18-50, savings bank account, consent for auto-debit',
  'Age 18-50, savings bank account, consent for auto-debit',
  'https://www.jansuraksha.gov.in/',
  true
),
(
  '10000000-0000-4000-8000-000000000004',
  'Atal Pension Yojana (APY)',
  'Atal Pension Yojana (APY)',
  'Atal Pension Yojana (APY)',
  'Pension scheme for unorganized sector workers providing guaranteed monthly pension after age 60 based on contribution amount.',
  'Pension scheme for unorganized sector workers providing guaranteed monthly pension after age 60 based on contribution amount.',
  'Pension scheme for unorganized sector workers providing guaranteed monthly pension after age 60 based on contribution amount.',
  'central',
  'Pension',
  'Unorganized workers, including auto and taxi drivers.',
  5000,
  'INR/month',
  'Age 18-40, savings bank account, not income tax payer',
  'Age 18-40, savings bank account, not income tax payer',
  'Age 18-40, savings bank account, not income tax payer',
  'https://www.npscra.nsdl.co.in/scheme-details.php',
  true
),
(
  '10000000-0000-4000-8000-000000000005',
  'E-Shram Registration',
  'E-Shram Registration',
  'E-Shram Registration',
  'Universal registration platform for unorganized workers including auto and taxi drivers. Provides access to welfare schemes and social security benefits.',
  'Universal registration platform for unorganized workers including auto and taxi drivers. Provides access to welfare schemes and social security benefits.',
  'Universal registration platform for unorganized workers including auto and taxi drivers. Provides access to welfare schemes and social security benefits.',
  'central',
  'Registration & Identity',
  'Unorganized workers, including drivers.',
  null,
  null,
  'Age 16-59, unorganized worker, valid mobile number and Aadhaar',
  'Age 16-59, unorganized worker, valid mobile number and Aadhaar',
  'Age 16-59, unorganized worker, valid mobile number and Aadhaar',
  'https://eshram.gov.in/',
  true
),
(
  '10000000-0000-4000-8000-000000000006',
  'Pradhan Mantri Shram Yogi Maandhan (PM-SYM)',
  'Pradhan Mantri Shram Yogi Maandhan (PM-SYM)',
  'Pradhan Mantri Shram Yogi Maandhan (PM-SYM)',
  'Voluntary contributory pension scheme for unorganized workers with assured monthly pension after the age of 60.',
  'Voluntary contributory pension scheme for unorganized workers with assured monthly pension after the age of 60.',
  'Voluntary contributory pension scheme for unorganized workers with assured monthly pension after the age of 60.',
  'central',
  'Pension',
  'Unorganized workers with modest monthly income.',
  3000,
  'INR/month',
  'Age 18-40, unorganized worker, not covered under EPFO/ESIC/NPS',
  'Age 18-40, unorganized worker, not covered under EPFO/ESIC/NPS',
  'Age 18-40, unorganized worker, not covered under EPFO/ESIC/NPS',
  'https://maandhan.in/',
  true
),
(
  '10000000-0000-4000-8000-000000000007',
  'Pradhan Mantri Mudra Yojana',
  'Pradhan Mantri Mudra Yojana',
  'Pradhan Mantri Mudra Yojana',
  'Business loan support for small entrepreneurs and self-employed workers to buy, repair, or expand income-generating vehicles and services.',
  'Business loan support for small entrepreneurs and self-employed workers to buy, repair, or expand income-generating vehicles and services.',
  'Business loan support for small entrepreneurs and self-employed workers to buy, repair, or expand income-generating vehicles and services.',
  'central',
  'Financial Support',
  'Self-employed drivers and small transport service operators.',
  1000000,
  'INR loan',
  'Non-corporate small business or self-employed applicant',
  'Non-corporate small business or self-employed applicant',
  'Non-corporate small business or self-employed applicant',
  'https://www.mudra.org.in/',
  true
),
(
  '10000000-0000-4000-8000-000000000008',
  'Educational Assistance for Drivers Children',
  'Educational Assistance for Drivers Children',
  'Educational Assistance for Drivers Children',
  'Financial assistance for education of drivers children from Class 1 to college level. Scholarship amount varies by course and eligibility.',
  'Financial assistance for education of drivers children from Class 1 to college level. Scholarship amount varies by course and eligibility.',
  'Financial assistance for education of drivers children from Class 1 to college level. Scholarship amount varies by course and eligibility.',
  'state',
  'Education',
  'Registered drivers and their dependent children.',
  10000,
  'INR/year',
  'Parent must be registered driver for minimum 3 years, child studying in recognized institution',
  'Parent must be registered driver for minimum 3 years, child studying in recognized institution',
  'Parent must be registered driver for minimum 3 years, child studying in recognized institution',
  null,
  true
),
(
  '10000000-0000-4000-8000-000000000009',
  'Free Eye Check-up and Spectacles',
  'Free Eye Check-up and Spectacles',
  'Free Eye Check-up and Spectacles',
  'Eye screening support for drivers with assistance for spectacles, helping improve road safety and day-to-day work comfort.',
  'Eye screening support for drivers with assistance for spectacles, helping improve road safety and day-to-day work comfort.',
  'Eye screening support for drivers with assistance for spectacles, helping improve road safety and day-to-day work comfort.',
  'state',
  'Healthcare',
  'Registered auto, taxi, van, bus, and lorry drivers.',
  null,
  null,
  'Registered driver with valid ID and welfare board or association support documents',
  'Registered driver with valid ID and welfare board or association support documents',
  'Registered driver with valid ID and welfare board or association support documents',
  null,
  true
),
(
  '10000000-0000-4000-8000-000000000010',
  'Chief Minister Comprehensive Health Insurance Scheme',
  'Chief Minister Comprehensive Health Insurance Scheme',
  'Chief Minister Comprehensive Health Insurance Scheme',
  'Tamil Nadu health insurance support for eligible families to access approved hospital treatments through empanelled hospitals.',
  'Tamil Nadu health insurance support for eligible families to access approved hospital treatments through empanelled hospitals.',
  'Tamil Nadu health insurance support for eligible families to access approved hospital treatments through empanelled hospitals.',
  'state',
  'Healthcare',
  'Eligible Tamil Nadu resident families, including driver families.',
  500000,
  'INR/year',
  'Tamil Nadu family meeting income and scheme eligibility norms',
  'Tamil Nadu family meeting income and scheme eligibility norms',
  'Tamil Nadu family meeting income and scheme eligibility norms',
  'https://www.cmchistn.com/',
  true
),
(
  '10000000-0000-4000-8000-000000000011',
  'Medical Assistance for Critical Illness',
  'Medical Assistance for Critical Illness',
  'Medical Assistance for Critical Illness',
  'Financial assistance for serious illness treatment expenses for registered drivers and eligible family members.',
  'Financial assistance for serious illness treatment expenses for registered drivers and eligible family members.',
  'Financial assistance for serious illness treatment expenses for registered drivers and eligible family members.',
  'state',
  'Healthcare',
  'Registered drivers and eligible dependents.',
  100000,
  'INR',
  'Registered driver with medical certificate, bills, and required identity documents',
  'Registered driver with medical certificate, bills, and required identity documents',
  'Registered driver with medical certificate, bills, and required identity documents',
  null,
  true
),
(
  '10000000-0000-4000-8000-000000000012',
  'Tamil Nadu Unorganised Drivers Welfare Board Registration',
  'Tamil Nadu Unorganised Drivers Welfare Board Registration',
  'Tamil Nadu Unorganised Drivers Welfare Board Registration',
  'State welfare-board registration support for unorganized drivers to access education, medical, accident, and family welfare benefits.',
  'State welfare-board registration support for unorganized drivers to access education, medical, accident, and family welfare benefits.',
  'State welfare-board registration support for unorganized drivers to access education, medical, accident, and family welfare benefits.',
  'state',
  'Registration & Identity',
  'Tamil Nadu unorganized drivers.',
  null,
  null,
  'Tamil Nadu resident driver with valid licence, identity proof, and address proof',
  'Tamil Nadu resident driver with valid licence, identity proof, and address proof',
  'Tamil Nadu resident driver with valid licence, identity proof, and address proof',
  null,
  true
),
(
  '10000000-0000-4000-8000-000000000013',
  'Accident Relief and Death Assistance for Drivers',
  'Accident Relief and Death Assistance for Drivers',
  'Accident Relief and Death Assistance for Drivers',
  'State-level support for registered drivers or their families in case of accidental injury, disability, or death.',
  'State-level support for registered drivers or their families in case of accidental injury, disability, or death.',
  'State-level support for registered drivers or their families in case of accidental injury, disability, or death.',
  'state',
  'Insurance',
  'Registered drivers and nominee family members.',
  200000,
  'INR',
  'Registered driver, accident records, medical or death certificate, nominee documents',
  'Registered driver, accident records, medical or death certificate, nominee documents',
  'Registered driver, accident records, medical or death certificate, nominee documents',
  null,
  true
)
ON CONFLICT (id) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ta = EXCLUDED.title_ta,
  title_hi = EXCLUDED.title_hi,
  description_en = EXCLUDED.description_en,
  description_ta = EXCLUDED.description_ta,
  description_hi = EXCLUDED.description_hi,
  level = EXCLUDED.level,
  category = EXCLUDED.category,
  target_workers = EXCLUDED.target_workers,
  max_benefit_amount = EXCLUDED.max_benefit_amount,
  benefit_unit = EXCLUDED.benefit_unit,
  eligibility_summary_en = EXCLUDED.eligibility_summary_en,
  eligibility_summary_ta = EXCLUDED.eligibility_summary_ta,
  eligibility_summary_hi = EXCLUDED.eligibility_summary_hi,
  official_link = EXCLUDED.official_link,
  is_active = EXCLUDED.is_active,
  updated_at = now();
